from app.schemas.urgency import RecommendedProviderType


class DoctorDocumentGenerator:
    """Generates formatted markdown documents for doctor visits."""

    def generate_markdown(
        self,
        concerns: list[str],
        symptom_timeline: list[str],
        questions_to_ask: list[str],
        medications_to_mention: list[str],
        red_flags_to_watch: list[str],
        recommended_provider: RecommendedProviderType,
        summary: str = "",
    ) -> str:
        lines = ["# Vital AI — Doctor Visit Preparation\n"]

        if summary:
            lines += ["## Overview\n", summary, ""]

        lines.append("## Main Concerns\n")
        for c in concerns:
            lines.append(f"- {c}")
        lines.append("")

        if symptom_timeline:
            lines.append("## Symptom Timeline\n")
            for t in symptom_timeline:
                lines.append(f"- {t}")
            lines.append("")

        if questions_to_ask:
            lines.append("## Questions to Ask My Doctor\n")
            for q in questions_to_ask:
                lines.append(f"- {q}")
            lines.append("")

        if medications_to_mention:
            lines.append("## Medications & Allergies to Mention\n")
            for m in medications_to_mention:
                lines.append(f"- {m}")
            lines.append("")

        if red_flags_to_watch:
            lines.append("## Red Flags to Watch For\n")
            for r in red_flags_to_watch:
                lines.append(f"- {r}")
            lines.append("")

        lines.append("## Recommended Provider Type\n")
        lines.append(f"**{recommended_provider.specialty.replace('_', ' ').title()}**")
        if recommended_provider.reason:
            lines.append(f"\n{recommended_provider.reason}")

        lines.append("\n---\n*Generated by Vital AI. This document is for educational purposes only.*")

        return "\n".join(lines)


def get_doctor_document_generator() -> DoctorDocumentGenerator:
    return DoctorDocumentGenerator()
